version: "3.0"

services:
  mysql:
    image: mysql
    container_name: airlines-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql_folder/script/schema.sql:/docker-entrypoint-initdb.d/1.sql 
  
  
  python-mysql:
    image: mypython
    container_name: airlines-app
    build: 
      context: ./mysql_folder
   
    environment:
      - DB_URL=mysql
    depends_on:
      - mysql

volumes:
  mysql_data:




