version: "3.0"

services:
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.2
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - es-data:/var/lib/elasticsearch/data
    privileged: true
    networks:
      - es-net
    ports:
      - 9200:9200
    

  es_load:
    container_name: es-load-container
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    volumes:
      - es-data:/var/lib/elasticsearch/data
    networks:
      - es-net
    depends_on:
      - elasticsearch
    build:
      context: ./elasticsearch

  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:8.1.2
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    volumes:
      - es-data:/var/lib/elasticsearch/data
    
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

networks:
  es-net:
    driver: bridge

volumes:
  es-data: